Update

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -41,11 +41,14 @@ jobs:
       - uses: Swatinem/rust-cache@v2
         with:
           prefix-key: "stage-aarch64"
-          workspaces: "./backend -> target"
+          workspaces: "backend -> target"
           cache-on-failure: true
 
       - name: Debug Cache Content
-        run: ls -R backend/target || echo "Target directory not found"
+        run: |
+          ls -la
+          ls -la backend
+          ls -R backend/target || echo "Target directory not found"
 
       - name: Install Protoc
         uses: arduino/setup-protoc@v3
@@ -66,9 +69,9 @@ jobs:
         env:
           CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
 
-      - name: CDK Bootstrap
-        working-directory: infrastructure
-        run: npx cdk bootstrap
+      - name: Debug Content To Cache
+        run: |
+          ls -R backend/target || echo "Target directory not found"
 
       - name: CDK Deploy
         working-directory: infrastructure
